from lxml import etree as ET
from src.core.models import Product
from src.feed.labels import resolve_search_intent_with_source, resolve_segment_with_source
from src.feed.product_types import resolve_product_type_with_source
from src.feed.text_cleaning import finalize_description, normalize_title

GNS = "http://base.google.com/ns/1.0"
NSMAP = {"g": GNS}


def gtag(name: str) -> str:
    return f"{{{GNS}}}{name}"


def build_gmc_feed(products: list[Product], optimized_map: dict, price_buckets: dict[str, str], margin_map: dict[str, str], default_margin_percent: int, currency: str = "CZK") -> ET._ElementTree:
    rss = ET.Element("rss", nsmap=NSMAP, version="2.0")
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = "Optimized GMC Feed"
    ET.SubElement(channel, "link").text = "https://example.invalid/"
    ET.SubElement(channel, "description").text = "Generated by shopping-feed-ai-v2"

    for p in products:
        data = optimized_map.setdefault(p.item_id, {})
        item = ET.SubElement(channel, "item")
        final_title, title_changed_by_postprocess = normalize_title(data.get("title") or p.title)
        params_map = {param.name: param.value for param in p.params if param.name}
        description, description_source = finalize_description(
            ai_description=data.get("description", ""),
            raw_html_or_text=p.description_html,
            title=final_title,
            category=p.category_text,
            params=params_map,
        )
        original_fallback_description, _ = finalize_description(
            ai_description="",
            raw_html_or_text=p.description_html,
            title=final_title,
            category=p.category_text,
            params=params_map,
        )
        product_type, product_type_source, product_type_reason = resolve_product_type_with_source(
            ai_product_type=data.get("product_type", ""),
            original_category=p.category_text,
            title=final_title,
            description=description,
            params=params_map,
        )
        search_intent, search_intent_source, search_intent_reason = resolve_search_intent_with_source(
            ai_value=data.get("search_intent", ""),
            title=final_title,
            description=description,
            category=p.category_text,
            params=params_map,
        )
        segment, segment_source, segment_reason = resolve_segment_with_source(
            ai_value=data.get("segment", ""),
            title=final_title,
            description=description,
            category=p.category_text,
            params=params_map,
        )
        # Internal debug marker helps trace whether the final value came from AI or fallback logic.
        data["_product_type_source"] = product_type_source
        data["_product_type_reason"] = product_type_reason
        data["_search_intent_source"] = search_intent_source
        data["_search_intent_reason"] = search_intent_reason
        data["_segment_source"] = segment_source
        data["_segment_reason"] = segment_reason
        data["_final_title"] = final_title
        data["_title_changed"] = final_title != p.title
        data["_title_changed_by_postprocess"] = title_changed_by_postprocess
        data["_final_description"] = description
        data["_description_source"] = description_source
        data["_description_changed"] = description != original_fallback_description
        data["_final_product_type"] = product_type
        data["_final_search_intent"] = search_intent
        data["_final_segment"] = segment
        ET.SubElement(item, gtag("id")).text = p.item_id
        ET.SubElement(item, "title").text = final_title
        ET.SubElement(item, "description").text = description
        ET.SubElement(item, "link").text = p.url
        ET.SubElement(item, gtag("image_link")).text = p.image_url
        for img in p.additional_images:
            ET.SubElement(item, gtag("additional_image_link")).text = img
        final_price = f"{str(p.price_vat).replace(',', '.')} {currency}" if currency not in p.price_vat else p.price_vat
        data["_final_price"] = final_price
        ET.SubElement(item, gtag("price")).text = final_price
        ET.SubElement(item, gtag("condition")).text = "new"
        availability = "in stock" if (p.delivery_date or "") in {"0", "1"} else "out of stock"
        data["_availability"] = availability
        ET.SubElement(item, gtag("availability")).text = availability
        ET.SubElement(item, gtag("product_type")).text = product_type
        if p.item_group_id:
            ET.SubElement(item, gtag("item_group_id")).text = p.item_group_id
        if data.get("gtin"):
            ET.SubElement(item, gtag("gtin")).text = data["gtin"]
        ET.SubElement(item, gtag("identifier_exists")).text = "FALSE"
        for d in p.deliveries:
            ship = ET.SubElement(item, gtag("shipping"))
            ET.SubElement(ship, gtag("country")).text = "CZ"
            ET.SubElement(ship, gtag("service")).text = d.delivery_id
            ET.SubElement(ship, gtag("price")).text = f"{str(d.price).replace(',', '.')} {currency}"
        custom_label_0 = margin_map.get(p.item_id, f"margin_{int(default_margin_percent)}")
        custom_label_1 = price_buckets.get(p.item_id, "price_unknown")
        data["_final_custom_label_0"] = custom_label_0
        data["_final_custom_label_1"] = custom_label_1
        ET.SubElement(item, gtag("custom_label_0")).text = custom_label_0
        ET.SubElement(item, gtag("custom_label_1")).text = custom_label_1
        ET.SubElement(item, gtag("custom_label_3")).text = search_intent
        ET.SubElement(item, gtag("custom_label_4")).text = segment
    return ET.ElementTree(rss)
